// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jddyoatbnfqxnzxewnmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZHlvYXRibmZxeG56eGV3bm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzY4MzcsImV4cCI6MjA2MDcxMjgzN30.1aknLxHu1Gx8Tha8MX6AhqeSe8ozWnCgkR78hPw3Gvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);